import Head from 'next/head'
import Home from 'components/Home'
import PostBox from '../../../../src/components/posts/PostBox/PostBox'
import PostHeader from '../../../../src/components/posts/postHeader/postHeader'

import PostBody from 'components/posts/PostBody/PostBody'
import Page from 'components/layout/page/page'
import {
    BOOK_MARK_SIDEBAR,
    PROFILE_SIDEBAR,
} from 'components/layout/sideBar/sideBarType'
import FeedList from 'components/feedBox/FeedList/FeedList'
import { useGetbookmark } from 'Hoocks'
import { useRouter } from 'next/router'
import { useSelector } from 'react-redux'
import { accessToken } from 'store/fetchers/authSlice'
interface optionprops {}

const BookMarkPost: React.FC<optionprops> = (props): JSX.Element => {
    const access = useSelector(accessToken)
    const { query } = useRouter()

    const { data: post, isLoading } = useGetbookmark(
        query?.bookMarkPost,
        access
    )
    return (
        <div>
            <Head>
                <title>نام بوک مارک </title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Page sideBar={[PROFILE_SIDEBAR]}>
                <FeedList
                    posts={post}
                    isLoading={isLoading}
                    FeedHeaderProps={true}
                />
            </Page>
        </div>
    )
}

export default BookMarkPost
