import Page from 'components/layout/page/page'
import {
    BOOK_MARK_SIDEBAR,
    PROFILE_SIDEBAR,
} from 'components/layout/sideBar/sideBarType'
import PostBody from 'components/posts/PostBody/PostBody'
import PostEdit from 'components/posts/Postedit/PostEdit'
import Head from 'next/head'
import { useEffect, useRef, useState } from 'react'
import { Button, Upload } from 'antd'
interface optionprops {}

const EditPost: React.FC<optionprops> = (props): JSX.Element => {
    const [editorLoaded, setEditorLoaded] = useState(false)

    useEffect(() => {
        setEditorLoaded(true)
    }, [])
    return (
        <div>
            <Head>
                <title>ویرایش پست</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Page sideBar={[BOOK_MARK_SIDEBAR, PROFILE_SIDEBAR]}>
                <PostBody>
                    <PostEdit editorLoaded={editorLoaded} />
                </PostBody>
            </Page>
        </div>
    )
}

export default EditPost
