import { fetchSinglePost } from 'api'
import Page from 'components/layout/page/page'
import SinglePostst from 'components/posts/singlePost/SinglePost'

import Head from 'next/head'
import { useRouter } from 'next/router'
// import SinglePost from 'components/posts/singlePost/SinglePost'
interface optionprops {
  data: any
}
const SinglePost: React.FC<optionprops> = ({ data }): JSX.Element => {
  const router = useRouter()
  const { postId } = router.query

  return (
    <div>
      <Head>
        <title>{data.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Page sideBar={null}>
        <SinglePostst data={data} />
      </Page>
    </div>
  )
}

export default SinglePost
export async function getServerSideProps({ params }) {
  const data = await fetchSinglePost(params.postId)

  return {
    props: { data },
  }
}
