import console from 'console'
import Head from 'next/head'
import { useRouter } from 'next/router'

interface optionprops {
  post: any
}
const SinglePost: React.FC<optionprops> = ({ post }): JSX.Element => {
  const router = useRouter()
  const { postId } = router.query
  return (
    <div>
      <Head>
        <title>پست ها</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{post.title}</h1>
      <div dangerouslySetInnerHTML={{ __html: post.body }}></div>
    </div>
  )
}

export default SinglePost
export async function getStaticProps({ params }) {
  const post = await fetch(
    `https://api.royaltiti.com/api/blog/blog_post/get_post/?seo_name=${params.postId}`
  ).then((res) => res.json())
  return {
    props: {
      post,
    },
  }
}
export async function getStaticPaths() {
  const posts = await fetch(
    'https://api.royaltiti.com/api/blog/blog_post/top_new_posts/'
  ).then((res) => res.json())

  const paths = posts.results.map((post) => ({
    params: { postId: post.seo_name },
  }))

  return {
    paths,
    fallback: false,
  }
}
