import Head from 'next/head'

interface optionprops {
  postsVal: any
}
const HomePage: React.FC<optionprops> = ({ postsVal }): JSX.Element => {
  return (
    <div>
      <Head>
        <title>پست ها</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default HomePage
export async function getStaticProps() {
  const posts = await fetch(
    'https://api.royaltiti.com/api/blog/blog_post/top_new_posts/'
  ).then((res) => res.json())

  return {
    props: {
      postsVal: posts,
    },
  }
}
