import React from "react";
import Head from "next/head";
import Page from "components/layout/page/page";
import BookMark from "components/bookmark/BookMark";

const Home: React.FC = (): JSX.Element => {
  return (
    <div>
      <Head>
        <title>صفحه اصلی</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BookMark />
    </div>
  );
};

export default Home;
