import React from "react";
import Head from "next/head";
import Page from "components/layout/page/page";

// import Layout from "layout/Layout";
import BookMarkBody from "components/bookmark/BookMarkBody/BookMarkBody";

const Home: React.FC = (): JSX.Element => {
  return (
    <div>
      <Head>
        <title>صفحه اصلی</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Layout> */}
      <Page sideBar="BookMark">
        <BookMarkBody />
      </Page>
      {/* </Layout> */}
    </div>
  );
};

export default Home;
