import React from 'react'
import Head from 'next/head'
import Page from 'components/layout/page/page'
import { useEffect } from 'react'
// import Layout from "layout/Layout";
import BookMarkBody from 'components/bookmark/BookMarkBody/BookMarkBody'
import {
    BOOK_MARK_SIDEBAR,
    PROFILE_SIDEBAR,
} from 'components/layout/sideBar/sideBarType'

import ToggleAccess from 'components/layout/toggleAccess'

const Home: React.FC = (): JSX.Element => {
    return (
        <div>
            <ToggleAccess />
            <Head>
                <title>لیست ها</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Page sideBar={[BOOK_MARK_SIDEBAR, PROFILE_SIDEBAR]}>
                <BookMarkBody />
            </Page>
        </div>
    )
}

export default Home
