import React from "react";
import Head from "next/head";

<<<<<<< HEAD
import Modal from "components/Modal";
import Auth from "components/Auth";
import Layout from "layout/Layout";
import FeedBox from "components/feedBox/FeedBox";
=======
import Home from "components/Home";
>>>>>>> ali

const HomePage: React.FC = (): JSX.Element => {
  return (
    <div>
      <Head>
        <title>صفحه اصلی</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<<<<<<< HEAD

      <Layout>
        <FeedBox />
      </Layout>
=======
      <Home />
>>>>>>> ali
    </div>
  );
};

export default Home;
