import Head from 'next/head'
import Home from 'components/Home'

const HomePage: React.FC = (): JSX.Element => {
  return (
    <div>
      <Head>
        <title>صفحه اصلی</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </div>
  )
}

export default Home
