import Head from 'next/head'
import Home from 'components/Home'
import PostBox from '../../../src/components/posts/PostBox/PostBox'
import PostHeader from '../../../src/components/posts/postHeader/postHeader'
import { useRouter } from 'next/router'
import PostBody from 'components/posts/PostBody/PostBody'
import Page from 'components/layout/page/page'
import {
    BOOK_MARK_SIDEBAR,
    PROFILE_SIDEBAR,
} from 'components/layout/sideBar/sideBarType'
interface optionprops {}

const HomePage: React.FC<optionprops> = (props): JSX.Element => {
    return (
        <div>
            <Head>
                <title>نمایش پست ها</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Page sideBar={[PROFILE_SIDEBAR]}>
                <PostBody>
                    <PostHeader />
                    <PostBox />
                </PostBody>
            </Page>
        </div>
    )
}

export default HomePage
